name: RM demo on Chrome

on: [push]

jobs:
    install:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
            uses: actions/Checkout@v2

            - name: Cypress run
            uses: cypress-io/github-action@v6
            with:
                project: ./e2e
                browser: chrome
                build: npm run build
                start: npm start
                wait-on: "http://www.amazon.com"