name: RM demo on Chrome

on: [push]

jobs:
    install:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/Checkout@v4
            - name: Run Cypress 
              uses: cypress-io/github-action@v6
              with:
                  browser: chrome
                  wait-on: "http://www.amazon.com"
            - name: Upload screenshots
              uses: actions/upload-artifact@v3
              if: failure()
              with:
                name: cypress-screenshots
                path: cypress/screenshots